[2025-10-11T06:27:55.160+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-11T04:04:30+00:00 [queued]>
[2025-10-11T06:27:55.163+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-11T04:04:30+00:00 [queued]>
[2025-10-11T06:27:55.163+0200] {taskinstance.py:2193} INFO - Starting attempt 6 of 1
[2025-10-11T06:27:55.168+0200] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): send_batch_predictions> on 2025-10-11 04:04:30+00:00
[2025-10-11T06:27:55.173+0200] {standard_task_runner.py:60} INFO - Started process 99762 to run task
[2025-10-11T06:27:55.176+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_batch_dag', 'send_batch_predictions', 'scheduled__2025-10-11T04:04:30+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/var/folders/rp/syznybx160jd0kg9k7r_sj8w0000gn/T/tmpjo33aqs2']
[2025-10-11T06:27:55.178+0200] {standard_task_runner.py:88} INFO - Job 165: Subtask send_batch_predictions
[2025-10-11T06:27:55.196+0200] {task_command.py:423} INFO - Running <TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-11T04:04:30+00:00 [running]> on host ebots-macbook-pro.local
[2025-10-11T06:27:55.215+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='predict_batch_dag' AIRFLOW_CTX_TASK_ID='send_batch_predictions' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T04:04:30+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-11T04:04:30+00:00'
[2025-10-11T06:27:55.216+0200] {prediction_dag.py:44} INFO - ðŸ“„ Found CSV file: /Users/ebotfabien/Desktop/school/air_new/dags/destination/data_part_1.csv
[2025-10-11T06:27:55.223+0200] {prediction_dag.py:70} INFO - ðŸ“¦ Sending 10 batch(es)...
[2025-10-11T06:27:55.223+0200] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ebotfabien/Desktop/school/all_dsp_venv/real_air/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/ebotfabien/Desktop/school/all_dsp_venv/real_air/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/ebotfabien/Desktop/school/all_dsp_venv/real_air/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/Users/ebotfabien/Desktop/school/all_dsp_venv/real_air/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/Users/ebotfabien/Desktop/school/all_dsp_venv/real_air/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/ebotfabien/Desktop/school/air_new/dags/prediction_dag.py", line 74, in send_batch_predictions
    logging(num_batches)
TypeError: 'module' object is not callable
[2025-10-11T06:27:55.226+0200] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=predict_batch_dag, task_id=send_batch_predictions, execution_date=20251011T040430, start_date=20251011T042755, end_date=20251011T042755
[2025-10-11T06:27:55.230+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 165 for task send_batch_predictions ('module' object is not callable; 99762)
[2025-10-11T06:27:55.265+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-11T06:27:55.303+0200] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
